@startmindmap
* ARC
** About
*** /site/about/
** Getting Started
*** /getting-started/
*** /site/guides/mods/
*** /site/guides/photo-mode/
** Guides
*** Installing Mods
*** UI Setup Tips
*** FAQ
** Creators
*** /creators/
**** Ilja Jusupov
**** Peter Boese
** Mods
*** Essentials List
** Meta
*** Contributors
*** Content Plan
@endmindmap
